"""delete user created field

Revision ID: 3dcd1e4f2edd
Revises: 7b59a97da181
Create Date: 2020-01-23 20:30:11.067724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dcd1e4f2edd'
down_revision = '7b59a97da181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
